# Generated by Django 3.0.3 on 2020-07-29 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Device', '0003_auto_20200727_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.CharField(default='Speed', max_length=200)),
                ('logitude', models.CharField(default='Longitude', max_length=200)),
                ('latitude', models.CharField(default='Latitude', max_length=200)),
                ('live_image', models.ImageField(blank=True, upload_to='live_image')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='Device.Device')),
            ],
        ),
    ]
